### ISSUE TITLE
Q: Did you manage to send custom keyboard?

### ISSUE THREAD

**Issue by BatuhanK** [mast/telegram-bot-api#1]
Hello, I tried almost 40 times to send custom keyboard layout, but it didn't worked.
Apperantly I'm doing something wrong, did you try to send custom keyboard layout?

**Comment by mast** [comment]
Hi,

Yes, it works fine for me. You need to have Telegram app updated with this feature support. Just make sure you have latest version from AppStore. And then the code is:

```
var keyboard = {
        keyboard: [
                ['Answer 1', 'Answer 2']
        ]
};

api.sendMessage({
        chat_id: <your chat id>
        text: 'Hello from brain with answers',
        reply_markup: JSON.stringify(keyboard)
}, function(err, data)
{
        console.log(util.inspect(data, false, null));
});
```

**Comment by BatuhanK** [comment]
@mast Thank you, I was doing the same but my Telegram app is not updated.
