### ISSUE TITLE
Migrate to es6

### ISSUE THREAD

**Issue by AliMD** [mast/telegram-bot-api#11]
I want to rewrite code to es6 with babeljs.
Make a pull or own repo ?

**Comment by mast** [comment]
I want to keep it as node.js module, and as far as I know es6 is very poorly supported by nodejs right now.
So there are 2 options:
- we do that as separate branch, or
- you do it as separate repo

**Comment by AliMD** [comment]
Please check this website babeljs.io
I think you don't really know it
It fully compatible as a simple node.js module

**Comment by derhuerst** [comment]
Even though using babeljs with regular Node.js is possible, why not wait until ES6 is natively supported?

**Comment by AliMD** [comment]
Es6  work a polyfill in next 3 years
And babeljs not a converter it rub es6 on the fly
Check my bot source code and read more about babeljs and/or typescript
https://github.com/AliMD/OneCastBot

**Comment by derhuerst** [comment]
> Es6 work a polyfill in next 3 years

What do you mean by that?

> And babeljs not a converter it rub es6 on the fly

[It is a converter](https://github.com/babel/babel/blob/master/packages/babel/src/api/register/node.js). It works like [`coffee-script/register`](https://github.com/jashkenas/coffeescript/blob/master/lib/coffee-script/register.js).

**Comment by AliMD** [comment]
Check my repo, it's work without convert, not like coffee
For example let work as let not as a var

**Comment by mast** [comment]
Ok, I got it now. So we can create es6 code and use babeljs for getting it executed with node at run time (as I see you managed to get it working in your referred repo).
Mainly I agree with @derhuerst and probably it's better to wait for native es6 support. But give me a chance to think about it a little bit more.
By the way what benefits of using es6 in bot api you see, @AliMD ?

**Comment by derhuerst** [comment]
> Check my repo, it's work without convert, not like coffee

[In your repo, you `require` `babel/register`](https://github.com/AliMD/OneCastBot/blob/master/index.js), which registers a hook that converts ES6 into ES5 (on the fly), just like CoffeeScript.

> Es6 work a polyfill in next 3 years

Since [io.js is close to `3.0.0`](https://github.com/nodejs/io.js/issues/1807) and [brings native ES6 support](https://iojs.org/en/es6.html), I don't think it's going to be 3 years, rather a few months. That's the reason I propose to wait with the migration until ES6 is natively supported.

**Comment by AliMD** [comment]
sorry, 3 years just for browser not node ;)
By the way i start it as my own repo and will continue this conversation after some time
Thank you

**Comment by AliMD** [comment]
@derhuerst 
Its time to use es6 ;)
