### ISSUE TITLE
Confused with reply_markup

### ISSUE THREAD

**Issue by iMasoud** [mast/telegram-bot-api#14]
Hi. I'm trying to change Keyboard after sending a photo, this is my code:

*...
		api.sendPhoto(
		{
		    chat_id: message.chat.id,
		    caption: '',
   		    photo: 'img/help.png',
	 	    reply_markup: {"keyboard" : [['help more!'],['cancel']]}
		}, function(err, data)
		{
...*

and this is the console output:
*{}*

can you give me an example about syntax of "reply_markup", please?

thank you and excuse me for my bad English

**Comment by iMasoud** [comment]
sorry for leaving an spam but it's really urgent!

can any one help me in this please?

**Comment by mast** [comment]
@iMasoud, did you try solution described here?
https://github.com/mast/telegram-bot-api/issues/1

**Comment by iMasoud** [comment]
wow, great! 

thankyou very much for your answer and for your great module! :+1:
