### ISSUE TITLE
Let sendDocument and sendPhoto take a stream instead of a filename

### ISSUE THREAD

**Issue by patrick246** [mast/telegram-bot-api#16]
I'm writing a bot where I download Pictures and Videos and send them over Telegram. To do that with the current API I need to save the HTTP Stream to a file and then let the API read that file. With a small change to those functions I'm able to pass them a stream and they send it happily.

**Comment by derhuerst** [comment]
Besides more elegant and efficient code, using streams would make *telegram-bot-api* more unopinionated because it doesn't force you to work with files.

**Comment by mast** [comment]
Fixed in 2.0
