### ISSUE TITLE
Bug: inline query

### ISSUE THREAD

**Issue by AliMD** [mast/telegram-bot-api#25]
Bot closed at inlineQuery
```
[TelegramBot]: Failed to get updates from Telegram servers
```

Error sent from `.catch` of `internalGetUpdates`

**Comment by jkantr** [comment]
This is unlikely to be a bug. Change the console.err of that catch to actually output the err param and see what the cause if the error is.

**Comment by AliMD** [comment]
error object is empty !!!

**Comment by AliMD** [comment]
I don't understand how to prevent bot closed!
How can skip this error ?
I removed console.error but bot still closed on any inlineQuery !

**Comment by AliMD** [comment]
@jkantr error object is empty !!!

**Comment by jkantr** [comment]
There is something wrong with your code. Removing the log of the error does
not remove the error, friend.

Instead change it to console.error(err) so you can tell me what the actual
error is. Please.

**Comment by jkantr** [comment]
If this is related to receiving an inline_query update?, I don't think the original lib here supports it. Is mast around? There was no response to the pull request. HelloWorld017's fork added the inlineQuery as well as approved the upstream request for my fork with support for callback_query updates as well as the new answerCallbackQuery and editMessageText request methods. So my suggestion would be to use one of our forks until we can get this all merged back pretty with the more visible of them (this one)

**Comment by AliMD** [comment]
> There is something wrong with your code.
No its not!  
I'm not a noob in javascript

> Removing the log of the error does not remove the error, friend.
I know that friend, i just want to say i don't know why program closed! i think it must just log the error not closed

> Instead change it to console.error(err) so you can tell me what the actual error is. Please.
I said error object is empty but you don't listening 


There is not my code error
I update #23 and problem fixed! Thank you.

**Comment by AliMD** [comment]
> I don't understand how to prevent bot closed!

I found it, app closed because there is no timeout for check new post not for that error.
You must add new timeout for `internalGetUpdates` after error!
```javascript
setTimeout(internalGetUpdates, _settings.updates.get_interval);
```
