### ISSUE TITLE
Adding a bot to the group and let it send messages without user input

### ISSUE THREAD

**Issue by Tiboonn** [mast/telegram-bot-api#51]
I would like to have my bot within a group/or channel and let it send messages to the group or channel.

`var api = new telegram({
    token: 'MY_TOKEN_HERE',
    updates: {
        enabled: true
    }
});
api.sendMessage({
                chat_id:,
                text: 'test TEXT'
            })
`

Right now the bot is sending the messages to the bot itself but not in the group where I added it as an admin. I also already change the privacy settings of the bot so it can see all messages.

**Comment by realestninja** [comment]
Did you insert the groups chat ID? Its a negative number.

**Comment by mast** [comment]
Closing this issue. You need to use proper chat_id for that.
