### ISSUE TITLE
issue with getChat 

### ISSUE THREAD

**Issue by DaniyalGeek** [mast/telegram-bot-api#52]
Hi,
i need to fetch chat from a channel as i doing right?
api.getChat({
                    chat_id: "@altcoins_signal"
                }, function(message)
{
	// New incoming callback query
    console.log(message);
});

**Comment by DaniyalGeek** [comment]
it's giving null in console

**Comment by mast** [comment]
I bet maybe bot should have permissions in that chat you want to get
