### ISSUE TITLE
bot over ipv6

### ISSUE THREAD

**Issue by mirisu2** [mast/telegram-bot-api#61]
Hi.
Is it possible to run bot over ipv6?
When I run application on node, I receive this error message:

> Error: RequestError: Error: connect ETIMEDOUT 149.154.167.220:443
>  at /var/www/telegram.bot/node_modules/telegram-bot-api/lib/telegram-bot.js:1686:19

I know, many telegram's ipv4 IPs blocked now. I have ipv6 address on server. If I `ping -4 api.telegram.org`, server cannot resolv address. If I `ping -6 api.telegram.org` - it works fine.

**Comment by V-MilkyWay** [comment]
Как ты это сделал????????????!!!!!)
