### ISSUE TITLE
Sending photos leads to error

### ISSUE THREAD

**Issue by ImbaKnugel** [mast/telegram-bot-api#7]
Sending a photo with a filepath leads to a Photo can't be empty error.
```javascript
    api.sendMessage({chat_id: chatID, text: image}, function(err, data)
    {
    if(err)
       log(err.description, 'Telegram-Server');
    });
```

**Comment by mast** [comment]
According to your code, you are sending text message, not a photo.
Correct way is:
```
api.sendPhoto({
    chat_id: <YOUR CHAT ID>,
    caption: 'This is my test image',

    // you can also send file_id here as string (as described in telegram bot api documentation)
    photo: '/path/to/file/test.jpg'
}, function(err, data)
{
    console.log(err);
    console.log(util.inspect(data, false, null));
});
```

**Comment by ImbaKnugel** [comment]
Soory I sendt the wrong code this is my api call. The file temp.png is in the same directory as the .js file
        api.sendPhoto({chat_id: chatID, photo: 'temp.png'}, function(err, data)
        {
          if(err)
            log(err.description, 'Telegram-Server');
        });

**Comment by mast** [comment]
I guess it's something wrong with your temp.png. Can you try to do "ls -la" and make sure that node can read this file and filename is correct? And also check file size. Are you sure that temp.png is a picture at all? Can you try with another png or jpg file?

The code I put above works fine for me (tried both png and jpg).

**Comment by ImbaKnugel** [comment]
Ok I found out that is was an error with wrong file extensions. Changing it to the correct extension fixed the error.
